from .base_agent import BaseAgent
from .agent_factory import AgentFactory

PLANNING_PROMPT = """\
You are a senior technical lead supervising the implementation of a simple landing page in HTML and CSS. Your role is to review the existing code generated by the agent and provide feedback and updates to the code. 

For each file you intend to change, you must provide a detailed plan of the changes you intend to make, return the suggested changes in the <delegate_agent_result> tag, as requested by the supervisor agent.
"
"""

class ReviewerAgent(BaseAgent):
    """A specialized agent for creating detailed webpage implementation plans."""
    
    def __init__(
        self,
        name: str = "Planning Agent",
        litellm_model: str = "anthropic/claude-3-5-sonnet-latest",
        model_kwargs=None
    ):
        """Initialize the planning agent with default settings.
        
        Args:
            name: Name of the agent
            litellm_model: Model identifier for litellm
            model_kwargs: Optional generation parameters
        """
        super().__init__(
            name=name,
            system_prompt=PLANNING_PROMPT,
            litellm_model=litellm_model,
            model_kwargs=model_kwargs
        )

# Register the agent with the factory
AgentFactory.register(ReviewerAgent) 